name: 'Build and test specfab'
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run:
          python -m pip install "numpy<2" "setuptools<65"
      - name: Build package
        working-directory: ./src
        run: |
          make all
          make python
