name: 'Build and test specfab'
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v4
      - name: Build package
        run: |
          cd src && make all
